// Copyright 2026 NoSQLBooster All rights reserved. Generated by NoSQLBooster 8.1.10
import mongoose from 'mongoose';
const { Schema } = mongoose;

const announcementsSchema = new Schema({
    date: Date,
    title: String,
    body: String,
    notify: Boolean,
    expires: Boolean,
    __v: Number
}, { collection: "announcements" });

const auctionsSchema = new Schema({
    ended: Boolean,
    cancelled: Boolean,
    price: Number,
    highBid: Number,
    cardID: Number,
    bids: [{
        user: String,
        bid: Number,
        time: Date
    }],
    auctionID: String,
    userID: String,
    lastBidderID: String,
    expires: Date,
    time: Date,
    guildID: String,
    __v: Number
}, { collection: "auctions" });

const cacheSchema = new Schema({
    key: String,
    expiration: Number,
    value: String
}, { collection: "cache" });

const cardsSchema = new Schema({
    stats: {
        soldToBot: [],
        auctionReturned: [{
            date: Date
        }],
        auctionSales: [{
            cost: Number,
            date: Date
        }],
        wishlistCount: Number,
        auctionCount: Number,
        totalCopies: Number
    },
    animated: Boolean,
    video: Boolean,
    canDrop: Boolean,
    ratingSum: Number,
    timesRated: Number,
    ownerCount: Number,
    cardID: Number,
    rarity: Number,
    collectionID: String,
    cardName: String,
    displayName: String,
    cardURL: String,
    added: Date,
    lastUpdatedEval: Date,
    "eval": Number,
    __v: Number,
    meta: {
        booruID: Number,
        booruScore: Number,
        booruRating: String,
        artist: String,
        pixivID: String,
        source: String,
        image: String,
        contributor: String,
        userID: String
    }
}, { collection: "cards" });

const claimsSchema = new Schema({
    claimID: String,
    lockCol: String,
    cardIDs: [Number],
    promo: Boolean,
    timeClaimed: Date,
    userID: String,
    guildID: String,
    cost: Number,
    __v: Number
}, { collection: "claims" });

const collectionsSchema = new Schema({
    stars: [String],
    aliases: [String],
    promo: Boolean,
    compressed: Boolean,
    inClaimPool: Boolean,
    dateAdded: Date,
    collectionID: String,
    name: String,
    origin: String,
    creatorID: String,
    __v: Number,
    rarity: Number
}, { collection: "collections" });

const guildbuildingsSchema = new Schema({
    level: Number,
    health: Number,
    guildID: String,
    buildingID: String,
    __v: Number
}, { collection: "guildbuildings" });

const guildsSchema = new Schema({
    lockCol: String,
    xp: Number,
    tax: Number,
    tomatoes: Number,
    lemons: Number,
    buildPerms: Number,
    discount: Number,
    heroLoyalty: Number,
    nextCheck: Date,
    lastLock: Date,
    adminLock: Boolean,
    lockActive: Boolean,
    processing: Boolean,
    guildID: String,
    hero: String,
    __v: Number,
    reportChannel: String
}, { collection: "guilds" });

const guildusersSchema = new Schema({
    xp: Number,
    level: Number,
    donations: Number,
    roles: [String],
    userID: String,
    guildID: String,
    __v: Number
}, { collection: "guildusers" });

const herosSchema = new Schema({
    xp: Number,
    followers: Number,
    accepted: Boolean,
    active: Boolean,
    submitted: Date,
    pictures: [String],
    heroID: String,
    name: String,
    userID: String,
    __v: Number
}, { collection: "heros" });

const plotsSchema = new Schema({
    building: {
        installed: Date,
        lastCollected: Date,
        buildingID: String,
        level: Number,
        storedLemons: Number,
        storedCards: []
    },
    nextCheck: Date,
    guildID: String,
    userID: String,
    __v: Number
}, { collection: "plots" });

const promosSchema = new Schema({
    promoCurrency: String,
    isBoost: Boolean,
    isDiscount: Boolean,
    isBonus: Boolean,
    cardIDs: [Schema.Types.Mixed],
    promoID: String,
    promoName: String,
    starts: Date,
    expires: Date,
    __v: Number,
    dropRate: Number
}, { collection: "promos" });

const sessionsSchema = new Schema({
    _id: String,
    payload: String,
    last_activity: Number,
    user_id: Schema.Types.Mixed,
    ip_address: String,
    user_agent: String
}, { collection: "sessions" });

const supportsSchema = new Schema({
    received: Date,
    transactionID: String,
    url: String,
    type: String,
    amount: Number,
    __v: Number
}, { collection: "supports" });

const tagsSchema = new Schema({
    status: String,
    cardID: Number,
    upvotes: [String],
    downvotes: [String],
    tagName: String,
    userID: String,
    __v: Number
}, { collection: "tags" });

const transactionsSchema = new Schema({
    cardIDs: [Number],
    transactionID: String,
    toID: String,
    fromID: String,
    status: String,
    guildID: String,
    cost: Number,
    dateCreated: Date,
    __v: Number
}, { collection: "transactions" });

const usercardsSchema = new Schema({
    amount: Number,
    rating: Number,
    fav: Boolean,
    locked: Boolean,
    acquired: Date,
    userID: String,
    cardID: Number,
    __v: Number
}, { collection: "usercards" });

const usereffectsSchema = new Schema({
    notified: Boolean,
    userID: String,
    effectID: String,
    usesLeft: Number,
    cooldownEnds: Date,
    __v: Number,
    expires: Date
}, { collection: "usereffects" });

const userinventoriesSchema = new Schema({
    cards: [Number],
    id: String,
    userID: String,
    itemID: String,
    acquired: Date,
    type: String,
    __v: Number,
    collectionID: String
}, { collection: "userinventories" });

const userquestsSchema = new Schema({
    completed: Boolean,
    created: Date,
    expires: Date,
    userID: String,
    questID: String,
    type: String,
    __v: Number
}, { collection: "userquests" });

const usersSchema = new Schema({
    streaks: {
        effects: {
            memoryVal: Number,
            memoryBday: Number,
            memoryHall: Number,
            memoryXmas: Number,
            xmasSpace: Boolean,
            hallSpace: Boolean,
            bdaySpace: Boolean,
            valSpace: Boolean
        },
        daily: {
            count: Number,
            lastCount: Schema.Types.Mixed,
            lastReset: Schema.Types.Mixed
        },
        donations: {
            kofi: {
                streak: Number
            },
            patreon: Schema.Types.Mixed
        }
    },
    ban: {
        full: Boolean,
        embargo: Boolean,
        report: Boolean,
        tags: Number
    },
    preferences: {
        notify: {
            aucBidMe: Boolean,
            aucOutbid: Boolean,
            aucNewBid: Boolean,
            aucEnd: Boolean,
            announce: Boolean,
            daily: Boolean,
            completed: Boolean,
            effectEnd: Boolean
        },
        interact: {
            canHas: Boolean,
            canDiff: Boolean,
            canSell: Boolean
        },
        profile: {
            bio: String,
            title: String,
            color: String,
            card: String,
            favComplete: String,
            favClout: String
        },
        display: Schema.Types.Mixed
    },
    premium: {
        active: Boolean,
        expires: Date
    },
    tomatoes: Number,
    vials: Number,
    lemons: Number,
    promoBal: Number,
    xp: Number,
    completedCols: [{
        id: String,
        amount: Number,
        notified: Boolean
    }],
    cloutedCols: [{
        id: String,
        amount: Number
    }],
    achievements: [String],
    lastDaily: Date,
    lastAnnounce: Date,
    lastCards: [],
    dailyNotified: Boolean,
    heroSubmits: Number,
    roles: [String],
    userID: String,
    username: String,
    hero: String,
    heroChanged: Date,
    joined: Date,
    __v: Number,
    lastCard: Schema.Types.Mixed
}, { collection: "users" });

const userslotsSchema = new Schema({
    active: Boolean,
    userID: String,
    effectName: String,
    slotExpires: Schema.Types.Mixed,
    cooldown: Date,
    __v: Number
}, { collection: "userslots" });

const userstatsSchema = new Schema({
    claims: Number,
    promoclaims: Number,
    totalRegularClaims: Number,
    aucSell: Number,
    aucBid: Number,
    aucWin: Number,
    liquefy: Number,
    liquefy1: Number,
    liquefy2: Number,
    liquefy3: Number,
    draw: Number,
    draw1: Number,
    draw2: Number,
    draw3: Number,
    forge: Number,
    forge1: Number,
    forge2: Number,
    forge3: Number,
    tags: Number,
    rates: Number,
    wish: Number,
    userSell: Number,
    botSell: Number,
    userBuy: Number,
    tomatoIn: Number,
    tomatoOut: Number,
    promoIn: Number,
    promoOut: Number,
    vialIn: Number,
    vialOut: Number,
    lemonIn: Number,
    lemonOut: Number,
    store: Number,
    storePlot: Number,
    storeRecipe: Number,
    storeTicket: Number,
    storeBonus: Number,
    t1Quests: Number,
    t2Quests: Number,
    userID: String,
    daily: Date,
    __v: Number,
    t3Quests: Number,
    t4Quests: Number,
    t5Quests: Number,
    t6Quests: Number,
    promoClaims: Schema.Types.Mixed,
    forge4: Schema.Types.Mixed
}, { collection: "userstats" });

const userwishlistsSchema = new Schema({
    added: Date,
    userID: String,
    cardID: String,
    __v: Number
}, { collection: "userwishlists" });
